# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: San Andreas State DOJRP
subtitle: 欢迎加入圣安地列斯州紧急职业模拟
author: HerMa
timezone:

# Internationalization (i18n) Setting
language: # At present, only en、cn and tw are supported. You can customize the language，refer to `languages/en.yml`.
  - en
  - cn
langselect:
  enable: true # If open, it will automatically generation lang-select button.This button can jump in articles in different languages, but the articles must have the same name.
  options: # langselect button display options
    en: English
    cn: 简体中文
    # tw: 正體中文


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite-url      # Note: don't forget to modify the CNAME file to your url
root: /
permalink: :lang/:title/
permalink_defaults:

# CDN Setting
## Docs: https://www.jsdelivr.com/?docs=gh
## If Github Pages deploy，you can ues jsdelivr settings
#
# jsdelivr:
#   jsdelivr_url: https://cdn.jsdelivr.net/gh/
#   github_username: V-Vincen


# Custom Setting Start

# Site settings
SEOTitle: FiveM | SASDOJ
email: hexo-theme-livemylife@gmail.com
description: "欢迎加入圣安地列斯州紧急职业模拟"
keyword: "sasdoj,fivem,san andreas,HerMa,SASDOJ"
header-img: img/header_img/111.jpg
archives-img: img/header_img/6923de7c4116ceae60d5d75d2d6d6f47.jpg


# Favicon settings
favicon: img/avatar/ttttt.jpg


# Signature Setup
signature: true # show signature
signature-img: img/signature/myLogo256.png


# Wave settings
wave: true


# SNS Settings
# RSS: true
github_username: 少年太傲
twitter_username: HerMa000
bilibili_username: 少年太傲
# facebook_username:  
# linkedin_username:  
# zhihu_username: 
weibo_username: 


# Sidebar Settings
sidebar: true   # whether or not using Sidebar.
sidebar-about-description: "QQ群：691706259"
sidebar-avatar: img/avatar/DPS-22027-HERMA.jpg    # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- visitor   # busuanzi: https://busuanzi.ibruce.info/
- featured-tags
- short-about
- recent-posts
- friends-blog
- archive
- category


# widget behavior
## Archive
archive_type: 'monthly'
show_count: true

## Featured Tags
featured-tags: true   # whether or not using Feature-Tags
featured-condition-size: 0    # A tag will be featured if the size of it is more than this condition value

## Friends
friends: [
    {
        title: "HerMa",
        href: "https://space.bilibili.com/400876089"
    },{
        title: "panda",
        href: "https://space.bilibili.com/104144589?spm_id_from=333.999.0.0"
    },{
        title: "Hank",
        href: "https://www.youtube.com/@hankteng1024"
    },{
        title: "Wangshitong",
        href: "test"
    }
]


# Comment Settings

## Gitalk Settings
## Doc:https://github.com/gitalk/gitalk/blob/master/readme-cn.md
##
gitalk:
  owner:                          # 'GitHub repo owner'
  admin:                          # 'GitHub repo'
  repo:                           # ['GitHub repo owner and collaborators, only these guys can initialize github issues']
  clientID:                       # 'GitHub Application Client ID'
  clientSecret:                   # 'GitHub Application Client Secret'
  perPage: 10                     # Pagination size, with maximum 100.
  pagerDirection: last            # Comment sorting direction, available values are last and first.
  createIssueManually: false      # By default, Gitalk will create a corresponding github issue for your every single page automatically when the logined user is belong to the admin users. You can create it manually by setting this option to true
  language: en                    # Localization language key, en, zh-CN and zh-TW are currently available.
  maxCommentHeight: 250           # An optional number to limit comments' max height, over which comments will be folded.Default 250.
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token  # GitHub oauth request reverse proxy for CORS. For example, the demo url is 'https://cors-anywhere.herokuapp.com/https://github.com/login/oauth/access_token'.You should deploy your own proxy url as in this issue https://github.com/gitalk/gitalk/issues/429.


## Gitment Settings
## Doc:https://github.com/imsun/gitment
##
# gitment:
#   owner:                          # Your GitHub ID. Required.
#   repo:                           # The repository to store your comments. Make sure you're repo's owner. Required.
#   client_id:                      # GitHub client ID. Required.
#   client_secret:                  # GitHub client secret. Required.
#   desc:                           # An optional description for your page, used in issue's body. Default ''.
#   perPage: 10                     # An optional number to which comments will be paginated. Default 20.
#   maxCommentHeight: 250           # An optional number to limit comments' max height, over which comments will be folded. Default 250.

## Disqus settings
##
# disqus_username: your-disqus-ID


# Analytics settings

## Google Analytics
ga_track_id: UA-xxxxxx-xx   # Format: UA-xxxxxx-xx

## Baidu Analytics
ba_track_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

## Sitemap
sitemap:
  path: sitemap.xml

## Baidusitemap
baidusitemap:
    path: baidusitemap.xml

baidu_push: true

# Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:


# Writing
new_post_name: :lang/:title.md    # File name of new posts
default_layout: post
auto_spacing: true
titlecase: false    # Transform title into titlecase
# New option
# https://hexo.io/docs/configuration.html#Writing
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''


# Category & Tag
default_category: uncategorized
category_map:
tag_map:
home_posts_tag: true    # show posts tags


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
##
date_format: YYYY-MM-DD
time_format: HH:mm:ss
# New option
# https://hexo.io/docs/configuration#Date-Time-format
updated_option: date


# Pagination
## Set per_page to 0 to disable pagination
##
per_page: 10
pagination_dir: archives

# hexo-generator-i18n config
## Docs: https://github.com/xcatliu/hexo-generator-index-i18n
index_generator:
  per_page: 10
  pagination_dir: page
  path: ''
  order_by: -date

archive_generator:
  enabled: false
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  order_by: -date


# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
##
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'


# Build Settings
anchorjs: true    # if you want to customize anchor. check out line:26 of `anchorjs.ejs`


# article top
top: true


# WordCount Settings
## Dependencies: https://github.com/willin/hexo-wordcount
## Docs: https://www.npmjs.com/package/hexo-wordcount
##
wordcount: true


# Busuanzi Settings
## Dependencies: https://busuanzi.ibruce.info/
## Docs: https://ibruce.info/
busuanzi: true


# top scroll progress
scroll: true


# Tip
tip:
  enable: true
  # copyright: 本网站归属权为吉林省卓力生物科技有限责任公司所有丨统一社会信用代码91220821MABUNX4C35丨网上有害信息举报专区：中国互联网违法和不良信息举报中心


# Social Share Post
## Docs:https://github.com/overtrue/share.js
##
socialshare: true


# Viewer config
## Docs:https://github.com/fengyuanchen/viewer
## Demo:https://fengyuanchen.github.io/viewer/
##
viewer: true


# ThemeColor config
themecolor:
  enable: true
  mode: dark # themecolor mode light or dark, default light


# Mouseclick config
mouseclick:
  enable: true
  content:
    - 欢迎加入圣安地列斯州紧急职业模拟...
    - QQ群：691706259...
    - 目前服务器已经正式开放申请...
    - 服务器目前为全免费制度服务器...
    - 进入服务器流程较为繁琐，这也是为了保护所有玩家的游戏体验...
    - San Andreas State DOJRP...
    - QQ群：691706259...
    - 服务器连接地址(浏览器打开)：cfx.re/join/loykjj...
    - 欢迎加入圣安地列斯州紧急职业模拟...
  color:
    - '#9933CC'
    - '#339933'
    - '#66CCCC'
    - '#FF99CC'
    - '#CCCCFF'
    - '#6666CC'
    - '#663399'
    - '#66CC99'
    - '#FF0033'


# Ribbon config
ribbonDynamic: true


# Line config
bglinecanvas: true  # The special effects will take up a lot of cpu resorces, please open it carefully.


# Search Setting
## Search: https://go.kieran.top/post/45/
## Dependencies: https://github.com/V-Vincen/hexo-generator-zip-search
##
search:
  path: search.json
  zipPath: search.flv
  versionPath: searchVersion.json
  field: post
  trigger: auto   # if 'auto', trigger search by changing input;if 'manual', trigger search by pressing enter key or search button
  top_n_per_article: 1    # show top n results per article, show all results by setting to -1


# Theme config
## Themes: https://hexo.io/themes/
##
theme: livemylife


# Gitter
## Docs:https://gitter.im/?utm_source=left-menu-logo
##
gitter:
  room: your-community/your-room


# Deployment
## Docs: https://hexo.io/docs/deployment.html
##
deploy:
  type: git
  repo: git@gitee.com:sasdoj/sasdoj.git
  branch: <your-branch>